services:
  mongo:
    container_name: growthbook-mongo
    image: "mongo:latest"
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongodata:/data/db
  growthbook:
    container_name: growthbook-app
    image: "growthbook/growthbook:latest"
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "3100:3100"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb+srv://$MONGO_USER:$MONGO_PASSWORD@$MONGO_HOST/$MONGO_DATABASE?authSource=admin
      - APP_ORIGIN=$DROPLET_URL:3000
      - API_HOST=$DROPLET_URL:3100
      - JWT_SECRET=$JWT_SECRET
    volumes:
      - uploads:/usr/local/src/app/packages/back-end/uploads
volumes:
  uploads:
  mongodata:
